// tests go here; this will not be compiled when this package is used as a library
motorbit.Setting_the_on_board_lights(Offset.ONE, RgbColors.Red)
motorbit.Setting_the_on_board_lights(Offset.TWO, RgbColors.Red)
motorbit.Setting_the_on_board_lights(Offset.THREE, RgbColors.Red)
motorbit.Setting_the_on_board_lights(Offset.FOUR, RgbColors.Red)
basic.pause(100)
motorbit.Setting_the_on_board_lights(Offset.ONE, RgbColors.Green)
motorbit.Setting_the_on_board_lights(Offset.TWO, RgbColors.Green)
motorbit.Setting_the_on_board_lights(Offset.THREE, RgbColors.Green)
motorbit.Setting_the_on_board_lights(Offset.FOUR, RgbColors.Green)
basic.pause(100)
motorbit.Setting_the_on_board_lights(Offset.ONE, RgbColors.Blue)
motorbit.Setting_the_on_board_lights(Offset.TWO, RgbColors.Blue)
motorbit.Setting_the_on_board_lights(Offset.THREE, RgbColors.Blue)
motorbit.Setting_the_on_board_lights(Offset.FOUR, RgbColors.Blue)
basic.pause(100)
motorbit.close_all_the_on_board_lights()
music.playTone(262, music.beat(BeatFraction.Whole))
basic.pause(100)
music.stopAllSounds()
basic.forever(function () {
    motorbit.MotorRun(motorbit.Motors.M1, 255)
    motorbit.MotorRun(motorbit.Motors.M2, 255)
    motorbit.MotorRun(motorbit.Motors.M3, 255)
    motorbit.MotorRun(motorbit.Motors.M4, 255)
    basic.pause(1000)
    motorbit.MotorRun(motorbit.Motors.M1, -255)
    motorbit.MotorRun(motorbit.Motors.M2, -255)
    motorbit.MotorRun(motorbit.Motors.M3, -255)
    motorbit.MotorRun(motorbit.Motors.M4, -255)
    basic.pause(1000)
    motorbit.MotorRun(motorbit.Motors.M1, 0)
    motorbit.MotorRun(motorbit.Motors.M2, 0)
    motorbit.MotorRun(motorbit.Motors.M3, 0)
    motorbit.MotorRun(motorbit.Motors.M4, 0)
    basic.pause(1000)
})
